data:
  top_pairs: 
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
    - "ADAUSDT"
    - "XRPUSDT"
    - "LTCUSDT"
    - "LINKUSDT"
    - "DOTUSDT"
  raw_data_path: "r_bot/data/raw/"
  results_path: "r_bot/results/"
  processed_data_path: "r_bot/data/processed"
  interval: "15m"
  start_date: "05 Jan, 2018"
  end_date: "05 Jul, 2024"
  max_candles: 200000

mean_reversion:
  moving_average_period: 30
  bollinger_std_dev: 2
  zscore_window: 20
  zscore_threshold: 2.0
  buy_zscore: -2.1
  sell_zscore: 2.5

correlation:
  threshold: 0.6

optimization:
  parameters:
    moving_average_period: [5, 60]
    bollinger_std_dev: [0.5, 3.0]
    zscore_threshold: [0.5, 2.5]
    zscore_window: [10, 60]
  metric: 'calmar_ratio'

bounds:
  moving_avg: [10, 100]
  std_dev: [1, 3]
  zscore_threshold: [1, 3]

analysis:
  correlation_threshold: 0.6  # Añadido para que coincida con el código
  coint_threshold: 0.4
  coint_significance: 0.05
